server:
  port: 18083
spring:
  application:
    name: wms-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.74.58:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.74.58
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml  # \u8BFB\u53D6\u6620\u5C04\u6587\u4EF6
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto  # \u9ED8\u8BA4\u4F7F\u7528\u6570\u636E\u5E93\u81EA\u589E
feign:
  sentinel:
    enabled: true

